# Author: Lenard Felix, Raphael Eiden

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, ClassVar, Mapping, Self

from shared.lib.error import parse_error_payload
from shared.lib.snapshot import parse_room_snapshot_payload
from shared.protocol import Message, make_message
from shared.schema import ErrorPayload, RoomSnapshotPayload
from shared.utils.ids import new_message_id


@dataclass(frozen=True, kw_only=True)
class Event(ABC):
    """Typed protocol event used by dispatchers and handlers."""

    message_type: ClassVar[str]
    """The unique identifier for the event type"""

    message_id: str = field(default_factory=new_message_id)
    """A unique identifier for the event instance (usually generated by the ids module and a prefixed UUID4)"""


    @abstractmethod
    def to_payload(self) -> Mapping[str, Any]:
        """Serialize the event-specific payload for transport."""
        raise NotImplementedError

    def to_message(self) -> Message:
        """Serialize the event into the wire-level message envelope."""
        msg = make_message(self.message_type, self.to_payload())
        msg["id"] = self.message_id
        return msg

    @classmethod
    @abstractmethod
    def from_message(cls, msg: Message) -> Self | None:
        """
        Converts the given message to an event instance.
        This method will automatically return the concrete type indicated
        by the type prefix in the message.

        :param msg:  The raw message to convert.
        :return:     A concrete event instance with all the attributes
        """
        raise NotImplementedError


@dataclass(frozen=True)
class ClientJoinRoomEvent(Event):
    """Client request to join a room with a player name."""

    message_type = "client.room.join"

    room_id: str
    player_name: str

    def to_payload(self) -> Mapping[str, Any]:
        return {
            "room_id": self.room_id,
            "player_name": self.player_name,
        }

    @classmethod
    def from_message(cls, msg: Message) -> Self | None:
        room_id = msg["payload"].get("room_id")
        player_name = msg["payload"].get("player_name")
        if not isinstance(room_id, str) or not room_id.strip():
            return None
        if not isinstance(player_name, str) or not player_name.strip():
            return None

        return cls(
            message_id=msg["id"],
            room_id=room_id.strip(),
            player_name=player_name.strip(),
        )


@dataclass(frozen=True)
class ServerRoomSnapshotEvent(Event):
    """Server snapshot response for the current viewer."""

    message_type = "room.snapshot"

    payload: RoomSnapshotPayload

    def to_payload(self) -> Mapping[str, Any]:
        return self.payload

    @classmethod
    def from_message(cls, msg: Message) -> Self | None:
        payload = parse_room_snapshot_payload(msg["payload"])
        if payload is None:
            return None
        return cls(message_id=msg["id"], payload=payload)


@dataclass(frozen=True)
class ServerResponseErrorEvent(Event):
    """Server error response."""

    message_type = "response.error"

    code: str
    message: str

    def to_payload(self) -> Mapping[str, Any]:
        return {
            "code": self.code,
            "message": self.message,
        }

    @classmethod
    def from_message(cls, msg: Message) -> Self | None:
        payload: ErrorPayload | None = parse_error_payload(msg["payload"])
        if payload is None:
            return None
        return cls(
            message_id=msg["id"],
            code=payload["code"],
            message=payload["message"],
        )
