from abc import ABC
from uuid import UUID

from shared.models import GameData, PlayerData

class GameRepository(ABC):

    def find_by_game_id(self, game_id: UUID) -> GameData: ...

    def find_by_join_code(self, join_code: str) -> GameData: ...

    def create_game(self, board_size: int, leader_player_id: UUID) -> GameData: ...

    def delete_game(self, game_id: int): ...

    def update_game(self, new_game: GameData): ...

class PlayerRepository(ABC):

    def create_player(self, display_name: str, connection_id: str) -> PlayerData: ...

    def find_by_id(self, player_id: UUID) -> PlayerData: ...

    def update_player(self, player: Player) -> Player: ...