from abc import ABC
from uuid import UUID

from shared.models.models import Game, Player

class GameRepository(ABC):

    def find_by_game_id(self, game_id: UUID) -> Game: ...

    def find_by_join_code(self, join_code: str) -> Game: ...

    def create_game(self, board_size: int, leader_player_id: UUID) -> Game: ...

    def delete_game(self, game_id: int): ...

    def update_game(self, new_game: Game): ...

class PlayerRepository(ABC):

    def create_player(self, display_name: str, connection_id: str) -> Player: ...

    def find_by_id(self, player_id: UUID) -> Player: ...

    def update_player(self, player: Player) -> Player: ...